version: '3.8'

services:
  postgres-db-v3:
    image: postgres:15
    container_name: runexus-postgres-v3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: runexus
    ports:
      - "5435:5432"
    volumes:
      - komplett_db3-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-v3:
    build:
      context: ./backend
    container_name: runexus-backend-v3
    ports:
      - "8082:8080"
    depends_on:
      - postgres-db-v3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-v3:5432/runexus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

  frontend-v3:
    build:
      context: ./frontend
    container_name: runexus-frontend-v3
    ports:
      - "5175:80"
    depends_on:
      - backend-v3

volumes:
  komplett_db3-data:

